const translations={
my:{navVisa:"Visa Services",navReq:"Requirements",navApply:"Apply Visa",navStatus:"Check Status",navQueue:"Queue",pill:"Professional Visa Service",heroTitle:"N&M Travel မှ Visa ဝန်ဆောင်မှုကို လွယ်ကူမြန်ဆန်စွာ ရယူပါ",heroText:"China နှင့် Thailand Visa လျှောက်ထားခြင်း၊ လိုအပ်ချက်စစ်ဆေးခြင်းနှင့် Application Status ကြည့်ရှုခြင်းကို တစ်နေရာတည်းမှာ ပြုလုပ်နိုင်ပါတယ်။",applyNow:"Apply Visa",checkNow:"Check Status",quickTitle:"Quick Services",service1:"Application & document checking",service2:"Application support",service3:"Get / check queue number",service4:"FAQ support in 3 languages",visaTitle:"Visa Services",chinaDesc:"China Visa အမျိုးအစား၊ လိုအပ်ချက်များနှင့် Application Service များကို ဆက်သွယ်မေးမြန်းနိုင်ပါတယ်။",thaiDesc:"Thailand Visa လျှောက်ထားရန် လိုအပ်သော အချက်အလက်များနှင့် Service Support ရယူနိုင်ပါတယ်။",start:"Start Application →",futureTitle:"More Countries",futureDesc:"နောက်ပိုင်းတွင် အခြားနိုင်ငံများကို ဒီနေရာမှာ အလွယ်တကူ ထပ်ထည့်နိုင်ပါတယ်။",reqTitle:"Visa Requirements",noticeTitle:"Important:",noticeText:"Visa requirements များသည် Visa Type နှင့် Applicant အခြေအနေအလိုက် ပြောင်းလဲနိုင်သောကြောင့် N&M Travel မှ နောက်ဆုံးအချက်အလက်ကို အတည်ပြုပေးပါမည်။",applyTitle:"Online Visa Application",applySub:"အောက်ပါ Form ကို ဖြည့်ပြီး Application ID ရယူပါ။ ဒီ Version မှာ data ကို ဒီ browser ထဲမှာ demo အဖြစ်သိမ်းထားပါတယ်။",name:"Applicant Name",phone:"Phone Number",country:"Visa Country",visaType:"Visa Type",travelDate:"Expected Travel Date",note:"Note",submit:"Submit Application",statusTitle:"Check Application Status",check:"Check",queueTitle:"Queue",takeQueue:"Get Queue",aiTitle:"Visa မေးခွန်းများကို အမြန်ဖြေကြားပေးမည့် Assistant",aiText:"Production Version မှာ N&M Travel ရဲ့ Knowledge Base ကိုအသုံးပြုပြီး မြန်မာ / English / 中文 ဖြင့် အဖြေပြန်နိုင်အောင် ချိတ်ဆက်ပေးမယ်။",contact:"Start Application"},
en:{navVisa:"Visa Services",navReq:"Requirements",navApply:"Apply Visa",navStatus:"Check Status",navQueue:"Queue",pill:"Professional Visa Service",heroTitle:"Easy and fast visa services from N&M Travel",heroText:"Apply for China and Thailand visas, check requirements, and track your application in one place.",applyNow:"Apply Visa",checkNow:"Check Status",quickTitle:"Quick Services",service1:"Application & document checking",service2:"Application support",service3:"Get / check queue number",service4:"FAQ support in 3 languages",visaTitle:"Visa Services",chinaDesc:"Ask about China visa types, requirements, and application services.",thaiDesc:"Get support and information for Thailand visa applications.",start:"Start Application →",futureTitle:"More Countries",futureDesc:"More countries can be added easily later.",reqTitle:"Visa Requirements",noticeTitle:"Important:",noticeText:"Requirements may vary by visa type and applicant. N&M Travel will confirm the latest requirements.",applyTitle:"Online Visa Application",applySub:"Complete the form to receive an application ID. This version stores demo data in this browser only.",name:"Applicant Name",phone:"Phone Number",country:"Visa Country",visaType:"Visa Type",travelDate:"Expected Travel Date",note:"Note",submit:"Submit Application",statusTitle:"Check Application Status",check:"Check",queueTitle:"Queue",takeQueue:"Get Queue",aiTitle:"Visa Assistant",aiText:"The production version will connect an N&M Travel knowledge base and answer in Myanmar, English, and Chinese.",contact:"Start Application"},
zh:{navVisa:"签证服务",navReq:"材料要求",navApply:"申请签证",navStatus:"查询状态",navQueue:"排队号码",pill:"专业签证服务",heroTitle:"N&M Travel 提供简单快捷的签证服务",heroText:"在一个网站申请中国和泰国签证、查看材料要求并查询申请状态。",applyNow:"申请签证",checkNow:"查询状态",quickTitle:"快速服务",service1:"申请及材料检查",service2:"签证申请协助",service3:"获取/查询排队号码",service4:"三语常见问题支持",visaTitle:"签证服务",chinaDesc:"咨询中国签证类型、材料要求和申请服务。",thaiDesc:"获取泰国签证申请信息和服务支持。",start:"开始申请 →",futureTitle:"更多国家",futureDesc:"以后可以轻松增加更多国家。",reqTitle:"签证材料要求",noticeTitle:"重要：",noticeText:"材料要求可能因签证类型和申请人情况而变化，N&M Travel 将确认最新要求。",applyTitle:"在线签证申请",applySub:"填写表格后获得申请编号。本版本仅将演示数据保存在当前浏览器中。",name:"申请人姓名",phone:"电话号码",country:"签证国家",visaType:"签证类型",travelDate:"预计出行日期",note:"备注",submit:"提交申请",statusTitle:"查询申请状态",check:"查询",queueTitle:"排队号码",takeQueue:"获取号码",aiTitle:"签证智能助手",aiText:"正式版本将连接 N&M Travel 知识库，并支持缅甸语、英语和中文回答。",contact:"开始申请"}
};
function setLang(lang){document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});localStorage.setItem("nm_lang",lang)}
document.getElementById("lang").addEventListener("change",e=>setLang(e.target.value));
const savedLang=localStorage.getItem("nm_lang")||"my";document.getElementById("lang").value=savedLang;setLang(savedLang);

function getApps(){return JSON.parse(localStorage.getItem("nm_apps")||"[]")}
function saveApps(a){localStorage.setItem("nm_apps",JSON.stringify(a))}
document.getElementById("applicationForm").addEventListener("submit",e=>{
 e.preventDefault();const fd=new FormData(e.target);const apps=getApps();const id="VISA-"+new Date().getFullYear()+"-"+String(apps.length+1).padStart(4,"0");const country=fd.get("country");const prefix=country==="China"?"CN":"TH";const qKey="nm_"+prefix+"_queue";let q=Number(localStorage.getItem(qKey)||0)+1;localStorage.setItem(qKey,q);const queue=prefix+"-"+String(q).padStart(3,"0");
 const app={id,name:fd.get("name"),phone:fd.get("phone"),country,visaType:fd.get("visaType"),travelDate:fd.get("travelDate"),note:fd.get("note"),queue,status:"Waiting",created:new Date().toISOString()};apps.push(app);saveApps(apps);
 const r=document.getElementById("applicationResult");r.classList.remove("hidden");r.innerHTML="<b>Application submitted!</b><br>Application ID: <strong>"+id+"</strong><br>Queue Number: <strong>"+queue+"</strong><br>Status: Waiting";e.target.reset();
});
document.getElementById("statusBtn").addEventListener("click",()=>{
 const id=document.getElementById("statusId").value.trim().toUpperCase();const app=getApps().find(x=>x.id===id);const r=document.getElementById("statusResult");r.classList.remove("hidden");r.innerHTML=app?`<b>${app.id}</b><br>Country: ${app.country}<br>Queue: <strong>${app.queue}</strong><br>Status: <strong>${app.status}</strong>`:"Application not found.";
});
function takeQueue(prefix){const key="nm_"+prefix+"_queue";let q=Number(localStorage.getItem(key)||0)+1;localStorage.setItem(key,q);const n=prefix+"-"+String(q).padStart(3,"0");document.getElementById(prefix==="CN"?"cnQueue":"thQueue").textContent=n;const r=document.getElementById("queueResult");r.classList.remove("hidden");r.innerHTML="Your queue number is <strong>"+n+"</strong>."}
window.takeQueue=takeQueue;